addons:
  apt:
    packages:
      - build-essential
      - gfortran
      - libatlas-base-dev
      - libfreetype6-dev
      - libpng12-dev

language: python
python:
  - "2.7"

before_install: pip install -r requirements.txt

install: make ext

script: npamp/npamp.py `mktemp`
